Repository ETF-TAK/FE, pull requests merged in 2024-12, with the labels that each got.

#45 feat/#35-feat-etf-list-page
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#48 feat/#35-feat-etf-list-page
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#49 feat/#35-feat-etf-list-page-ui
  src/pages/listPage/style.css
Labels: style 🌏

#46 pr Feat/#39 basic info UI
  src/assets/images/common/sectors/gold.png
  src/assets/images/common/sectors/it.png
  src/pages/ComparePage.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/comparePage/style.css
  src/pages/scrollPage/ScrollPage.jsx
  src/pages/scrollPage/style.css
  src/routers/main-router.jsx
Labels: feat ✨, fix 🐞, design 🎨

#51 feat/#35-feat-etf-list-page-ui
  src/pages/listPage/style.css
Labels: style 🌏

#53 pr feat/#35-feat-etf-list-page-api
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
Labels: feat ✨

#56 pr feat/#35-feat-etf-list-page
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#59 pr feat/#54-connect-invest-api
  src/assets/images/sectors/circle/battery.png
  src/assets/images/sectors/circle/consumer.png
  src/assets/images/sectors/circle/default.png
  src/assets/images/sectors/circle/energy.png
  src/assets/images/sectors/circle/entertainment.png
  src/assets/images/sectors/circle/esg.png
  src/assets/images/sectors/circle/finance.png
  src/assets/images/sectors/circle/gold.png
  src/assets/images/sectors/circle/health.png
  src/assets/images/sectors/circle/it.png
  src/assets/images/sectors/circle/reits.png
  src/assets/images/sectors/circle/semiconductor.png
  src/assets/images/sectors/circle/ship.png
  src/assets/images/sectors/circle/snp500.png
  src/assets/images/sectors/circle/steel.png
  src/assets/images/sectors/circle/transport.png
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/components/etf/etfProfile/ETFProfile.jsx
  src/components/etf/etfProfile/style.css
  src/components/etf/sectorMapper/SectorMapper.jsx
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/components/invest/selectedETF/SelectedETF.jsx
  src/components/invest/selectedETF/style.css
  src/lib/apis/invest.js
  src/pages/investPage/InvestPage.jsx
  src/pages/investPage/investAmountPage/InvestAmountPage.jsx
  src/pages/investPage/investResult/InvestResult.jsx
Labels: feat ✨

#61 style(#35): 태그 호버
  src/components/tag/style.css
  src/pages/listPage/ListPage.jsx
Labels: style 🌏

#62 pr feat/#57-change-cursor
  src/components/common/test/questionCard/style.css
Labels: style 🌏

#65 pr feat/#63-etf-test-compare-link-value
  src/components/common/test/categoryCard/CategoryCard.jsx
  src/components/common/test/categoryCard/style.css
Labels: feat ✨

#66 pr feat/#64-sector-navigate-detail
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#67 pr feat/#52-connect-etf-detail
  src/assets/images/common/koreaInvest_answer.png
  src/assets/images/common/sectors/finance.png
  src/assets/images/common/sectors/semiconductor.png
  src/assets/images/common/sectors/us.png
  src/components/common/DetailTable.jsx
  src/components/common/ProductInfo.jsx
  src/components/common/WeightedTreemap.jsx
  src/pages/DetailPage.jsx
  src/pages/scrollPage/ScrollPage.jsx
Labels: feat ✨

#68 pr feat/#60-connect-etf-compare-page-api
  src/assets/images/sectors/noCircle/battery.png
  src/assets/images/sectors/noCircle/consumer.png
  src/assets/images/sectors/noCircle/default.png
  src/assets/images/sectors/noCircle/energy.png
  src/assets/images/sectors/noCircle/entertainment.png
  src/assets/images/sectors/noCircle/esg.png
  src/assets/images/sectors/noCircle/finance.png
  src/assets/images/sectors/noCircle/gold.png
  src/assets/images/sectors/noCircle/health.png
  src/assets/images/sectors/noCircle/it.png
  src/assets/images/sectors/noCircle/reits.png
  src/assets/images/sectors/noCircle/semiconductor.png
  src/assets/images/sectors/noCircle/ship.png
  src/assets/images/sectors/noCircle/snp500.png
  src/assets/images/sectors/noCircle/steel.png
  src/assets/images/sectors/noCircle/transport.png
  src/components/etf/compareCard/CompareCard.jsx
  src/components/etf/sectorMapper/SectorMapper.jsx
  src/components/etf/sectorMapper/SectorMapperNoCircle.jsx
  src/lib/apis/compare.js
  src/pages/comparePage/ComparePage.jsx
  src/pages/comparePage/style.css
  src/pages/mainPage/MainPage.jsx
  src/pages/scrollPage/ScrollPage.jsx
  src/pages/scrollPage/style.css
Labels: feat ✨

#70 pr feat/#64-etf-test-compare-link
  src/components/common/test/categoryCard/CategoryCard.jsx
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#72 pr feat/#71-etf-list-style
  src/pages/comparePage/ComparePage.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
Labels: style 🌏

#74 pr feat/#71feat/#71-compare-card-delete
  src/pages/comparePage/ComparePage.jsx
Labels: feat ✨

#75 pr fix/#71-compare-style
  src/components/tag/style.css
  src/pages/comparePage/ComparePage.jsx
Labels: fix 🐞

#76 pr feat/#69-update-etf-compare-page
  src/pages/DetailPage.jsx
  src/pages/scrollPage/ScrollPage.jsx
  src/pages/scrollPage/style.css
Labels: feat ✨

#78 pr feat/#73-component-event-guide
  src/pages/comparePage/ComparePage.jsx
Labels: feat ✨

#81 pr fix/#80-etf-unit-modification
  src/components/etf/compareCard/CompareCard.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/scrollPage/ScrollPage.jsx
Labels: fix 🐞

#83 pr fix/#82-net-worth-unit
  src/pages/scrollPage/ScrollPage.jsx
Labels: fix 🐞

#84 pr feat/#79-animation
  src/assets/images/icons/search_blue.png
  src/components/word/WordCard.jsx
  src/components/word/style.css
  src/pages/comparePage/style.css
  src/pages/guidePage/guideDetalPage/GuideDetailPage.jsx
  src/pages/guidePage/guideDetalPage/style.css
  src/pages/investPage/investAmountPage/style.css
  src/pages/investPage/investResult/InvestResult.jsx
  src/pages/investPage/investResult/style.css
  src/pages/investPage/style.css
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
  src/pages/testPage/style.css
  src/pages/testPage/testResultPage/style.css
Labels: feat ✨

#86 pr fix/#85-etf-invest-result-null-card
  src/assets/images/icons/sol_sorry.png
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/components/invest/investResultCard/style.css
  src/pages/investPage/investResult/InvestResult.jsx
Labels: fix 🐞

#87 deploy
  src/assets/images/icons/search_blue.png
  src/assets/images/icons/sol_sorry.png
  src/components/etf/compareCard/CompareCard.jsx
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/components/invest/investResultCard/style.css
  src/components/word/WordCard.jsx
  src/components/word/style.css
  src/pages/comparePage/ComparePage.jsx
  src/pages/comparePage/style.css
  src/pages/guidePage/guideDetalPage/GuideDetailPage.jsx
  src/pages/guidePage/guideDetalPage/style.css
  src/pages/investPage/investAmountPage/style.css
  src/pages/investPage/investResult/InvestResult.jsx
  src/pages/investPage/investResult/style.css
  src/pages/investPage/style.css
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
  src/pages/scrollPage/ScrollPage.jsx
  src/pages/testPage/style.css
  src/pages/testPage/testResultPage/style.css
Labels: deploy🚀

#90 pr feat/#88-connect-deploy-server-api
  .gitignore
  src/lib/apis/compare.js
  src/lib/apis/invest.js
  src/pages/DetailPage.jsx
  src/pages/listPage/ListPage.jsx
Labels: feat ✨

#91 deploy
  .gitignore
  src/lib/apis/compare.js
  src/lib/apis/invest.js
  src/pages/DetailPage.jsx
  src/pages/listPage/ListPage.jsx
Labels: deploy🚀

#92 pr feat/#89-sector-page-loading
  package-lock.json
  package.json
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
Labels: feat ✨

#93 pr feat/#89-compare-detail -page-loading
  src/lib/apis/compare.js
  src/pages/DetailPage.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/comparePage/style.css
Labels: feat ✨

#94 deploy
  package-lock.json
  package.json
  src/lib/apis/compare.js
  src/pages/DetailPage.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/comparePage/style.css
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
Labels: deploy🚀

#95 pr feat/#88-connect-deploy-server-api
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/pages/investPage/investResult/InvestResult.jsx
Labels: feat ✨

#96 depoly
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/pages/investPage/investResult/InvestResult.jsx
Labels: deploy🚀

#97 pr feat/#88-connect-deploy-server-api
  src/components/common/DetailTable.jsx
  src/components/common/WeightedTreemap.jsx
  src/components/common/test/categoryCard/CategoryCard.jsx
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/lib/apis/compare.js
  src/lib/apis/invest.js
  src/pages/DetailPage.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/guidePage/guidePages/GuidePage.jsx
  src/pages/investPage/InvestPage.jsx
  src/pages/investPage/investAmountPage/InvestAmountPage.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/scrollPage/ScrollPage.jsx
Labels: feat ✨

#98 deploy
  src/components/common/DetailTable.jsx
  src/components/common/WeightedTreemap.jsx
  src/components/common/test/categoryCard/CategoryCard.jsx
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/lib/apis/compare.js
  src/lib/apis/invest.js
  src/pages/DetailPage.jsx
  src/pages/comparePage/ComparePage.jsx
  src/pages/guidePage/guidePages/GuidePage.jsx
  src/pages/investPage/InvestPage.jsx
  src/pages/investPage/investAmountPage/InvestAmountPage.jsx
  src/pages/listPage/ListPage.jsx
  src/pages/scrollPage/ScrollPage.jsx
Labels: deploy🚀

#99 feat/#88-connect-deploy-server-api
  src/pages/DetailPage.jsx
Labels: fix 🐞

#101 pr feat/#88-connect-deploy-server api
  src/assets/images/common/sectors/korea.png
  src/assets/images/common/sectors/us.png
Labels: design 🎨

#100 deploy
  src/assets/images/common/sectors/korea.png
  src/assets/images/common/sectors/us.png
  src/pages/DetailPage.jsx
Labels: deploy🚀
