Repository ETF-TAK/FE, pull requests merged in 2024-11, with the labels that each got.

#2 pr feat#1-project-initial-setting
  .gitignore
  .prettierrc.cjs
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.jsx
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/images/common/logo.png
  src/assets/images/common/logoIcon.png
  src/assets/react.svg
  src/components/common/Layout.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/style.css
  src/index.css
  src/lib/apis/invest.js
  src/main.jsx
  src/pages/ComparePage.jsx
  src/pages/GuidePage.jsx
  src/pages/InvestPage.jsx
  src/pages/MainPage.jsx
  src/pages/TestPage.jsx
  src/routers/main-router.jsx
  vite.config.js
Labels: feat ✨

#7 pr feat/#5-etf-detail-ui
  .github/ISSUE_TEMPLATE/etf-tak-issue-template.md
  .prettierrc.cjs
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/common/question.png
  src/components/common/DetailTable.jsx
  src/components/common/ETFHeader.jsx
  src/components/common/Layout.jsx
  src/components/common/ProductInfo.jsx
  src/components/common/WeightedTreemap.jsx
  src/components/common/header/Header.jsx
  src/index.css
  src/lib/apis/data.js
  src/main.jsx
  src/pages/ComparePage.jsx
  src/pages/DetailPage.jsx
  src/pages/GuidePage.jsx
  src/pages/InvestPage.jsx
  src/pages/TestPage.jsx
  src/routers/main-router.jsx
  vite.config.js
Labels: feat ✨, style 🌏, setting :hammer_and_wrench:

#8 PR Feat/#4 etf compare UI
  package-lock.json
  package.json
  src/pages/ComparePage.jsx
  src/styles/ComparePage.css
Labels: feat ✨, setting :hammer_and_wrench:

#9 pr feat/#3-invest-page-u
  .vite/deps/_metadata.json
  .vite/deps/package.json
  package-lock.json
  package.json
  src/assets/images/common/sectors/korea.png
  src/assets/images/icons/delete.png
  src/components/etf/CategoryTabs/CategoryTabs.jsx
  src/components/etf/CategoryTabs/style.css
  src/components/etf/etfProfile/ETFProfile.jsx
  src/components/etf/etfProfile/style.css
  src/components/invest/investCard/InvestCard.jsx
  src/components/invest/investCard/style.css
  src/components/invest/investResultCard/InvestResultCard.jsx
  src/components/invest/investResultCard/style.css
  src/components/invest/resultConfetti/ResultConfetti.jsx
  src/components/invest/resultConfetti/useAccelation.jsx
  src/components/invest/resultRain/ResultRain.jsx
  src/components/invest/selectedETF/SelectedETF.jsx
  src/components/invest/selectedETF/style.css
  src/pages/InvestPage.jsx
  src/pages/investPage/InvestPage.jsx
  src/pages/investPage/investAmountPage/InvestAmountPage.jsx
  src/pages/investPage/investAmountPage/style.css
  src/pages/investPage/investResult/InvestResult.jsx
  src/pages/investPage/investResult/style.css
  src/pages/investPage/style.css
  src/routers/main-router.jsx
Labels: feat ✨

#12 pr feat/#11-tooltipbox-location
  package-lock.json
  src/pages/DetailPage.jsx
Labels: feat ✨

#13 pr fix/#10-fix-invest-page-ui
  src/components/common/header/Header.jsx
  src/pages/investPage/investAmountPage/style.css
  src/pages/investPage/style.css
Labels: fix 🐞

#17 pr feat/#6-etf-word-ui
  src/assets/images/word/word_card1.svg
  src/assets/images/word/word_card10.svg
  src/assets/images/word/word_card2.svg
  src/assets/images/word/word_card3.svg
  src/assets/images/word/word_card4.svg
  src/assets/images/word/word_card5.svg
  src/assets/images/word/word_card6.svg
  src/assets/images/word/word_card7.svg
  src/assets/images/word/word_card8.svg
  src/assets/images/word/word_card9.svg
  src/assets/images/wordDetail/content1.svg
  src/assets/images/wordDetail/content2.svg
  src/assets/images/wordDetail/content3.svg
  src/assets/images/wordDetail/content4.svg
  src/assets/images/wordDetail/content5.svg
  src/assets/images/wordDetail/content7.svg
  src/assets/images/wordDetail/content8.svg
  src/assets/images/wordDetail/content9.svg
  src/assets/images/wordDetail/word_detail1.svg
  src/assets/images/wordDetail/word_detail10.svg
  src/assets/images/wordDetail/word_detail2.svg
  src/assets/images/wordDetail/word_detail3.svg
  src/assets/images/wordDetail/word_detail4.svg
  src/assets/images/wordDetail/word_detail5.svg
  src/assets/images/wordDetail/word_detail6.svg
  src/assets/images/wordDetail/word_detail7.svg
  src/assets/images/wordDetail/word_detail8.svg
  src/assets/images/wordDetail/word_detail9.svg
  src/components/word/WordCard.jsx
  src/components/word/style.css
  src/pages/GuidePage.jsx
  src/pages/guidePage/guideDetalPage/ GuideDetailPage.jsx
  src/pages/guidePage/guideDetalPage/guideData.jsx
  src/pages/guidePage/guideDetalPage/style.css
  src/pages/guidePage/guidePages/GuidePage.jsx
  src/pages/guidePage/guidePages/style.css
  src/routers/main-router.jsx
Labels: feat ✨

#18 pr feat/#6-etf-word-ui
  src/pages/guidePage/guideDetalPage/GuideDetailPage.jsx
  src/routers/main-router.jsx
Labels: feat ✨

#20 pr feat/#19-distribution-field-and-header-active
  src/components/common/ProductInfo.jsx
  src/components/common/header/Header.jsx
  src/pages/DetailPage.jsx
Labels: feat ✨

#22 pr fix/#22-tooltipbox-location-modification
  src/pages/DetailPage.jsx
Labels: fix 🐞

#25 pr feat/#24-deploy-test
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/components/etf/categoryTabs/style.css
  src/pages/investPage/InvestPage.jsx
Labels: fix 🐞, deploy🚀

#27 pr feat/#26-deploy-setting-redirect
  vercel.json
Labels: deploy🚀

#28 Deploy
  vercel.json
Labels: deploy🚀

#37 pr feat/#36-edit-navbar
  src/components/common/header/Header.jsx
  src/components/common/header/style.css
  src/pages/listPage/ListPage.jsx
  src/routers/main-router.jsx
Labels: feat ✨

#42 pr feat/#40-update-etf-compare-page-ui
  src/assets/images/icons/search.png
  src/assets/images/sectors/gold.png
  src/components/etf/categoryTabs/CategoryTabs.jsx
  src/components/etf/compareCard/CompareCard.jsx
  src/components/etf/compareCard/style.css
  src/pages/ComparePage.jsx
  src/styles/ComparePage.css
Labels: feat ✨, design 🎨

#43 feat/#35-feat-etf-list-page
  package.json
  src/pages/listPage/ListPage.jsx
  src/pages/listPage/style.css
Labels: feat ✨

#44 feat(#35): 태그 검색 결과 리스트 출력
  src/pages/listPage/ListPage.jsx
Labels: feat ✨
